define([], function() {
    return [{
        id: 1,
        text: '1N',
        meridian: 'UB'
    }, {
        id: 3,
        text: '2N',
        meridian: 'UB'
    }, {
        id: 5,
        text: '3N',
        meridian: 'UB'
    }, {
        id: 7,
        text: '4N',
        meridian: 'UB'
    }, {
        id: 9,
        text: '5N',
        meridian: 'UB'
    }, {
        id: 2,
        text: '1S',
        meridian: 'UB'
    }, {
        id: 4,
        text: '2S',
        meridian: 'UB'
    }, {
        id: 6,
        text: '3S',
        meridian: 'UB'
    }, {
        id: 8,
        text: '4S',
        meridian: 'UB'
    }, {
        id: 10,
        text: '5S',
        meridian: 'UB'
    }, {
        id: 11,
        text: '6S',
        meridian: 'UB'
    }, {
        id: 12,
        text: '7S',
        meridian: 'UB'
    }, {
        id: 13,
        text: '1N',
        meridian: 'SL'
    }, {
        id: 16,
        text: '2N',
        meridian: 'SL'
    }, {
        id: 18,
        text: '3N',
        meridian: 'SL'
    }, {
        id: 20,
        text: '4N',
        meridian: 'SL'
    }, {
        id: 22,
        text: '5N',
        meridian: 'SL'
    }, {
        id: 24,
        text: '6N',
        meridian: 'SL'
    }, {
        id: 26,
        text: '7N',
        meridian: 'SL'
    }, {
        id: 28,
        text: '8N',
        meridian: 'SL'
    }, {
        id: 30,
        text: '9N',
        meridian: 'SL'
    }, {
        id: 32,
        text: '10N',
        meridian: 'SL'
    }, {
        id: 34,
        text: '10.5N',
        meridian: 'SL'
    }, {
        id: 35,
        text: '11N',
        meridian: 'SL'
    }, {
        id: 38,
        text: '12N',
        meridian: 'SL'
    }, {
        id: 40,
        text: '13N',
        meridian: 'SL'
    }, {
        id: 42,
        text: '14N',
        meridian: 'SL'
    }, {
        id: 44,
        text: '15N',
        meridian: 'SL'
    }, {
        id: 14,
        text: '1S',
        meridian: 'SL'
    }, {
        id: 15,
        text: '1.5S',
        meridian: 'SL'
    }, {
        id: 17,
        text: '2S',
        meridian: 'SL'
    }, {
        id: 19,
        text: '3S',
        meridian: 'SL'
    }, {
        id: 21,
        text: '4S',
        meridian: 'SL'
    }, {
        id: 23,
        text: '5S',
        meridian: 'SL'
    }, {
        id: 25,
        text: '6S',
        meridian: 'SL'
    }, {
        id: 27,
        text: '7S',
        meridian: 'SL'
    }, {
        id: 29,
        text: '8S',
        meridian: 'SL'
    }, {
        id: 31,
        text: '9S',
        meridian: 'SL'
    }, {
        id: 33,
        text: '10S',
        meridian: 'SL'
    }, {
        id: 36,
        text: '11S',
        meridian: 'SL'
    }, {
        id: 37,
        text: '11.5S',
        meridian: 'SL'
    }, {
        id: 39,
        text: '12S',
        meridian: 'SL'
    }, {
        id: 41,
        text: '13S',
        meridian: 'SL'
    }, {
        id: 43,
        text: '14S',
        meridian: 'SL'
    }, {
        id: 45,
        text: '15S',
        meridian: 'SL'
    }, {
        id: 46,
        text: '15.5S',
        meridian: 'SL'
    }, {
        id: 47,
        text: '16S',
        meridian: 'SL'
    }, {
        id: 48,
        text: '17S',
        meridian: 'SL'
    }, {
        id: 49,
        text: '18S',
        meridian: 'SL'
    }, {
        id: 50,
        text: '19S',
        meridian: 'SL'
    }, {
        id: 51,
        text: '19.5S',
        meridian: 'SL'
    }, {
        id: 52,
        text: '20S',
        meridian: 'SL'
    }, {
        id: 53,
        text: '20.5S',
        meridian: 'SL'
    }, {
        id: 54,
        text: '21S',
        meridian: 'SL'
    }, {
        id: 55,
        text: '22S',
        meridian: 'SL'
    }, {
        id: 56,
        text: '23S',
        meridian: 'SL'
    }, {
        id: 57,
        text: '24S',
        meridian: 'SL'
    }, {
        id: 58,
        text: '25S',
        meridian: 'SL'
    }, {
        id: 59,
        text: '26S',
        meridian: 'SL'
    }, {
        id: 60,
        text: '27S',
        meridian: 'SL'
    }, {
        id: 61,
        text: '28S',
        meridian: 'SL'
    }, {
        id: 62,
        text: '28.5S',
        meridian: 'SL'
    }, {
        id: 63,
        text: '29S',
        meridian: 'SL'
    }, {
        id: 64,
        text: '29.5S',
        meridian: 'SL'
    }, {
        id: 65,
        text: '30S',
        meridian: 'SL'
    }, {
        id: 66,
        text: '30.5S',
        meridian: 'SL'
    }, {
        id: 67,
        text: '31S',
        meridian: 'SL'
    }, {
        id: 68,
        text: '32S',
        meridian: 'SL'
    }, {
        id: 69,
        text: '32.5S',
        meridian: 'SL'
    }, {
        id: 70,
        text: '33S',
        meridian: 'SL'
    }, {
        id: 71,
        text: '34S',
        meridian: 'SL'
    }, {
        id: 72,
        text: '35S',
        meridian: 'SL'
    }, {
        id: 73,
        text: '35.5S',
        meridian: 'SL'
    }, {
        id: 74,
        text: '36S',
        meridian: 'SL'
    }, {
        id: 75,
        text: '37S',
        meridian: 'SL'
    }, {
        id: 76,
        text: '37.5S',
        meridian: 'SL'
    }, {
        id: 77,
        text: '38S',
        meridian: 'SL'
    }, {
        id: 78,
        text: '38.5S',
        meridian: 'SL'
    }, {
        id: 79,
        text: '39S',
        meridian: 'SL'
    }, {
        id: 80,
        text: '40S',
        meridian: 'SL'
    }, {
        id: 81,
        text: '40.5S',
        meridian: 'SL'
    }, {
        id: 82,
        text: '41S',
        meridian: 'SL'
    }, {
        id: 83,
        text: '42S',
        meridian: 'SL'
    }, {
        id: 84,
        text: '42.5S',
        meridian: 'SL'
    }, {
        id: 85,
        text: '43S',
        meridian: 'SL'
    }, {
        id: 86,
        text: '44S',
        meridian: 'SL'
    }];
});